### ISSUE TITLE
WARNING: deprecated syntax

### ISSUE THREAD

**Issue by mirestrepo** [bcbi/PubMedMiner.jl#1]
When searching, saving pubmed results:
WARNING: deprecated syntax "Clinics (" at /Users/isa/Dropbox/BrownAgain/Projects/BCBI/PubMedMiner.jl/exe/pubMedSearch.jl:1.
Use "Clinics(" instead.

Can't determine what package is triggering the warning

**Comment by paulstey** [comment]
I'm quite confident that this warning isn't at all related to the saving to database portion. I sometimes get this same warning when using `xml2dict()` in our XMLconvert package.

**Comment by mirestrepo** [comment]
I'm closing this as I think warnings from other packages are quite common these days :)
